### ISSUE TITLE
Kubernetes Deployment

### ISSUE THREAD

**Issue by sergeiwaigant** [brandond/syslog_ng_exporter#9]
Hi there.

any idea how to create some kind of symlinks on a shared volume to the required socket to be able to link the syslog-ng.ctl socket from the pod running syslog-ng with the pod running the exporter?

Regards
Sergei

**Comment by sergeiwaigant** [comment]
Never mind... found the solution...

1. Create a volume in `Deployment` or `StatefulSet`
```
      volumes:
        - name: tmp
          emptyDir: {}
```
2.  Add item to `args` and `volumeMounts`
```
          args:
            - --control=/tmp/syslog-ng.ctl
          ...
          volumeMounts:
            - name: tmp
              mountPath: /tmp
```
3. Add side car container
```
        - name: syslog-ng-exporter
          image: brandond/syslog_ng_exporter:0.1.1
          args:
            - --telemetry.address=:9577
            - --telemetry.endpoint=/metrics
            - --socket.path=/tmp/syslog-ng.ctl
            - --log.level=info
            - --log.format=logger:stdout?json=true
          ports:
            - name: metrics
              containerPort: 9577
              protocol: TCP
          volumeMounts:
            - name: tmp
              mountPath: /tmp
```
4. Add metrics port to `Service` object
```
ports:
    - port: 24231
      targetPort: metrics
      protocol: TCP
      name: metrics
```
5. Create `ServiceMonitor` object
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: syslog-central
    app.kubernetes.io/name: syslog-ng
  name: syslog-central
  namespace: syslog-ng
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: metrics
    scrapeTimeout: 5s
  jobLabel: syslog-ng-central
  namespaceSelector:
    matchNames:
    - syslog-ng
  selector:
    matchLabels:
      app.kubernetes.io/instance: syslog-central
      app.kubernetes.io/name: syslog-ng
```
